const FLAGS: Record<string, string> = {
  USA: "🇺🇸",
  Canada: "🇨🇦",
  Mexico: "🇲🇽",
  Brazil: "🇧🇷",
  Argentina: "🇦🇷",
  Colombia: "🇨🇴",
  Chile: "🇨🇱",
  UK: "🇬🇧",
  Germany: "🇩🇪",
  France: "🇫🇷",
  Netherlands: "🇳🇱",
  Switzerland: "🇨🇭",
  Spain: "🇪🇸",
  Italy: "🇮🇹",
  Denmark: "🇩🇰",
  Finland: "🇫🇮",
  Sweden: "🇸🇪",
  Norway: "🇳🇴",
  Poland: "🇵🇱",
  Ireland: "🇮🇪",
  Belgium: "🇧🇪",
  Austria: "🇦🇹",
  Portugal: "🇵🇹",
  Japan: "🇯🇵",
  China: "🇨🇳",
  "South Korea": "🇰🇷",
  Taiwan: "🇹🇼",
  India: "🇮🇳",
  Singapore: "🇸🇬",
  Indonesia: "🇮🇩",
  Philippines: "🇵🇭",
  Thailand: "🇹🇭",
  Vietnam: "🇻🇳",
  "Saudi Arabia": "🇸🇦",
  UAE: "🇦🇪",
  Qatar: "🇶🇦",
  Israel: "🇮🇱",
  Turkey: "🇹🇷",
  Egypt: "🇪🇬",
  "South Africa": "🇿🇦",
  Nigeria: "🇳🇬",
  Kenya: "🇰🇪",
  Australia: "🇦🇺",
  "New Zealand": "🇳🇿",
};

export function flagFor(country: string): string {
  return FLAGS[country] ?? "🏳️";
}
